# Generated by Django 5.2.7 on 2025-10-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='habilidades',
        ),
        migrations.AlterField(
            model_name='personaje',
            name='equipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='poder',
            field=models.CharField(max_length=100),
        ),
    ]
